sentry:
  dsn: '%env(SENTRY_DSN)%'
  options:
    environment: '%env(SENTRY_ENVIRONMENT)%'
    release: '%env(SENTRY_RELEASE)%'

#  skip_capture:  # To skip certain exceptions, specify a list below
#    - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
#    - 'Symfony\Component\HttpKernel\Exception\BadRequestHttpException'
#    - 'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException'
