parameters:
  paste.ttl: 604800
  redis.scheme: 'tcp'
  redis.host: 'localhost'
  redis.port: 6379
  tpl.dir: '%kernel.root_dir%/templates'

framework:
  secret: '%secret%'
  http_method_override: true
  router:
    resource: '%kernel.root_dir%/config/routing.prod.yml'
    strict_requirements: '%kernel.debug%'
  templating:
    engines: ['twig']
  session:
    cookie_secure: true

monolog:
  handlers:
    main:
      type: 'fingers_crossed'
      action_level: 'notice'
      handler: 'nested'
    nested:
      type: 'stream'
      path: '%kernel.logs_dir%/%kernel.name%.log'
      level: 'debug'

twig:
  paths: ['%kernel.root_dir%/templates']

services:

  predis.client:
    class: 'Predis\Client'
    arguments:
      -
        scheme: '%redis.scheme%'
        host: '%redis.host%'
        port: '%redis.port%'

  paste.cache:
    class: 'Doctrine\Common\Cache\PredisCache'
    arguments: [ '@predis.client' ]
  paste.hash_generator:
    class: 'Alcohol\Paste\Security\HashGenerator'
    arguments: [ '%secret%' ]
  paste.repository:
    class: 'Alcohol\Paste\Repository\PasteRepository'
    arguments: [ '@paste.cache', '%paste.ttl%' ]

  paste.controller.index:
    class: 'Alcohol\Paste\Controller\IndexController'
    arguments: [ '@templating', '@router' ]
  paste.controller.create:
    class: 'Alcohol\Paste\Controller\CreateController'
    arguments: [ '@templating', '@router', '@paste.repository' ]
  paste.controller.read:
    class: 'Alcohol\Paste\Controller\ReadController'
    arguments: [ '@templating', '@router', '@paste.repository' ]
  paste.controller.update:
    class: 'Alcohol\Paste\Controller\UpdateController'
    arguments: [ '@paste.repository' ]
  paste.controller.delete:
    class: 'Alcohol\Paste\Controller\DeleteController'
    arguments: [ '@paste.repository' ]

  paste.kernel.exception_listener:
    class: 'Alcohol\Paste\EventListener\ExceptionListener'
    arguments: [ '@logger' ]
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'handleEvent' }
  paste.kernel.request_listener:
    class: 'Alcohol\Paste\EventListener\RequestListener'
    arguments: [ '@paste.hash_generator' ]
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.request', method: 'handleEvent' }
  paste.kernel.response_listener:
    class: 'Alcohol\Paste\EventListener\ResponseListener'
    arguments: [ '@paste.hash_generator' ]
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.response', method: 'handleEvent' }

  paste.command.read:
    class: 'Alcohol\Paste\Console\Command\ReadCommand'
    arguments: [ '@paste.repository' ]
    tags:
      - { name: 'console.command' }
  paste.command.delete:
    class: 'Alcohol\Paste\Console\Command\DeleteCommand'
    arguments: [ '@paste.repository' ]
    tags:
      - { name: 'console.command' }
